baseURL: https://caelanjmiller.github.io/
languageCode: en-us
title: Caelan Miller
theme: PaperMod

# Parameters for Profile PaperMod Theme
params:
  env: production
  defaultTheme: auto
  disableThemeToggle: false
  ShowBreadCrumbs: true
  ShowReadingTime: true
  label:
    text: Home
    icon: img/virus_white.png
    iconHeight: 35

# Search Parameters
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  assets:
    favicon: "img/favicon.ico"
    favicon16x16: "img/favicon-16x16.png"
    favicon32x32: "img/favicon-32x32.png"
    apple_touch_icon: "img/apple-touch-icon.png"
  
  profileMode:
    enabled: true
    title: "<Title>" 
    subtitle: "PhD Student in Computational & Systems Biology [@WUSTL](https://dbbs.wustl.edu)"
    imageUrl: "img/Miller_Caelan.jpeg"
    imageTitle: "Profile Image of Caelan Miller"
    imageWidth: 300 
    imageHeight: 300

  socialIcons:
    - name: github
      url: "https://github.com/caelanjmiller"
    - name: linkedin
      url: "https://www.linkedin.com/in/caelan-miller"
    - name: email
      url: "mailto:caelanjmiller@wustl.edu"
    - name: orcid
      url: "https://orcid.org/0009-0001-5944-2327"

# Adds Main Navbar Links
menu:
  main:
    - identifier: cv
      name: CV
      url: /cv
      weight: 10
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50

# Allows for Search Functionality Amongst Posts
outputs:
  home:
    - HTML
    - RSS
    - JSON